cielo:
  visa: :cielo_visa
  mastercard: :cielo_mastercard
  americanexpress: :cielo_amex
  diners: :cielo_diners
  hipercard: :sitef_hipercard

redecard:
  visa: :redecard_visa
  mastercard: :redecard_mastercard
  americanexpress: :sitef_amex
  diners: :redecard_diners
  hipercard: :sitef_hipercard

teste:
  visa: :homolog
  mastercard: :homolog
  americanexpress: :homolog
  diners: :homolog
  hipercard: :homolog