test:
  search_domain: search-test-olook-products-2ykpfrclwbu55oirdfgjmvuvsu.us-east-1.cloudsearch.amazonaws.com
  docs_domain: doc-test-olook-products-2ykpfrclwbu55oirdfgjmvuvsu.us-east-1.cloudsearch.amazonaws.com
  api_version:  "2011-02-01"

development:
  docs_domain:  doc-busca-psk3zhncl4g2kbsvt7q4u6467a.sa-east-1.cloudsearch.amazonaws.com
  search_domain: search-busca-psk3zhncl4g2kbsvt7q4u6467a.sa-east-1.cloudsearch.amazonaws.com
  api_version:  "2013-01-01"

staging:
  search_domain: search-test-olook-products-2ykpfrclwbu55oirdfgjmvuvsu.us-east-1.cloudsearch.amazonaws.com
  docs_domain: doc-test-olook-products-2ykpfrclwbu55oirdfgjmvuvsu.us-east-1.cloudsearch.amazonaws.com
  api_version:  "2011-02-01"

production:
  docs_domain:  doc-busca-psk3zhncl4g2kbsvt7q4u6467a.sa-east-1.cloudsearch.amazonaws.com
  search_domain: search-busca-psk3zhncl4g2kbsvt7q4u6467a.sa-east-1.cloudsearch.amazonaws.com
  api_version:  "2013-01-01"
