campaigns:
  - Flyers
  - Blogueiras
  - Clubes de compra
  - Parcerias
  - Promoção POM
  - Aniversariantes
  - Reativação por e-mail
  - Promoções em Social Media
  - Recompra por e-mail
  - Pesquisa pós compra
  - Troca e Devolução
