defaults: &defaults
  products_blacklist:
    - 1
    - 127
    - 778
    - 823
    - 1174
    - 12472
  collections_blacklist:
    - 1
    - 2
    - 4
    - 6
    - 8
    - 9
    - 10
    - 11

development:
  <<: *defaults

staging:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
